services:
    api:
        build: GradProjectServer
        depends_on:
            - broker
        ports:
            - 1234:1234
        networks:
            - marje3
    
    broker:
        build: DockerBroker
        networks:
            - marje3
networks:
    marje3:
