services:
    api:
        build: 
            context: .
            dockerfile: GradProjectServer-Dockerfile
            args:
                HostUserId: '1000'
                HostGroupId: '1000'
        depends_on:
            - broker
            - db
        ports:
            - 1234:1234
        networks:
            - marje3network
        volumes:
            - '/home/abdallah/Desktop/GraduationProject/Data:/app/data/'
    
    broker:
        build:
            context: .
            dockerfile: DockerBroker-Dockerfile
        ports:
            - 1235:1235
            - 1236:1236
            - 1237:1237
        networks:
            - marje3network
    
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "marje3"
            POSTGRES_USER: "marje3"
            POSTGRES_DB: "postgres"
        expose:
            - 5432
        networks:
            - marje3network
        
networks:
    marje3network:
